### ISSUE TITLE
AI part doesnt work

### ISSUE THREAD

**Issue by Martin-SF** [kvgc/arxiv-shorts#8]
**doesnt work** (only a blank space under the abstract appears)
- An AI generated summary of the abstract
- A list of concepts needed to understand the abstract, including a brief explanation of their importance and how they are used in the abstract.
- Other relevant papers to read (experimental).

**do work**
- Load arxiv pdf on the same page
- Search for astrobites articles that cover the paper.
- Annotate pdfs using [hypothes.is](https://prod.outgoing.prod.webservices.mozgcp.net/v1/33de7e4387f906e50f59a3acc987dc8f1cd6633fc4e4dd8e99326058da4a9d27/http%3A//hypothes.is)

i also tested with any other plugin deactivated  
Firefox 122.0 64bit Macbook air M2

**Comment by kvgc** [comment]
Hi @Martin-SF 
Thanks!
I can reproduce this issue on the recent arXiv submissions. 
It looks like the AI block does not render. Let me try to fix this later today. 
The extension seems to work fine on the older submissions (e.g., https://arxiv.org/abs/2306.03120v1).
kvgc

**Comment by Martin-SF** [comment]
Hey kvgc! 
Thanks for looking into the issue :)

That sounds good although im not sure if the problem is purely time-dependent. 
Your example works for me, but not any iam currently working with. 
for example https://arxiv.org/abs/2310.08845 or https://arxiv.org/abs/2005.10665 or https://arxiv.org/abs/1905.02773

**Comment by kvgc** [comment]
Hi @Martin-SF ,
I have resolved this issue in most of the recent papers. 
Will have to run some more tests to ensure that its working alright on all of them.
Regarding your second query, the AI summaries are currently only available for astro-ph.GA articles. The other arXiv categories are still in the works.
Hope this helps!
kvgc
